export const popularCategories = [
    'Body Massage Centres',
    'Cinema Halls',
    'Schools',
    'Beauty Spas',
    'Dermatologists',
    'Hospitals',
    'Malls',
    'Gyms',
    'Beauty Parlours',
    'Estate Agents',
    'Banquet Halls',
    'ENT Doctors',
    'Book Shops',
    'Bike On Rent',
    'Sexologist Doctors',
    'Neurologists',
    'Gynaecologist & Obstetrician Doctors',
    'Tiffin Services',
    'Travel Agents',
    'Paying Guest Accommodations',
    'General Physician Doctors',
    'Dentists',
    'Orthopaedic Doctors',
    'Chemists',
    'Motor Training Schools',
    'Gastroenterologists',
    'Car Rental',
    'Salons',
    'Courier Services',
    'Dance Classes',
    'Pathology Labs',
    'Taxi Services',
    'Cake Shops',
    'AC Repair & Services',
    'Mobile Phone Dealers',
    'Pet Shops',
    'Dmart',
    'Packers And Movers',
    'Psychiatrists',
    'Dharamshalas',
    'Urologist Doctors',
    'Bakeries',
    'Bicycle Dealers',
    'Coffee Shops',
    'Paediatricians',
    'Sonography Centres',
    'Yoga Classes',
    'Hostels',
    'Cardiologists',
    'Electrical Shops',
    'Skin Care Clinics',
    'Diagnostic Centres',
    'Homeopathic Doctors',
    'Physiotherapists',
    'Photo Studios',
    'Plumbers',
    'Music Classes',
    'Electricians',
    'Sports Goods Dealers',
    'Shoe Dealers',
    'Hair Stylists',
    'Gift Shops',
    'Ophthalmologists',
    'Car Repair & Services',
    'Ayurvedic Doctors',
    'Eye Clinics',
    'Restaurants',
    'Carpenters',
    'Jewellery Showrooms',
    'Cooks On Hire',
    'Stationery Shops',
    'Nephrologists',
    'Caterers',
    'Interior Designers',
    'Rehabilitation Center',
    'Drug De Addiction Center',
    'Grocery Stores',
    'AC Repair',
    'Hotels',
    'Cab & Car Rental',
    'Spa & Salon',
    'Car service',
    'Lab Test',
    'On Demand Service',
    'JdSocial Blog',
    'JD collections',
];
